// examples/vue3/src/App.vue
<template>
  <div>
    ToS
    <adyen-terms-of-service
      :rootlegalentityid="rootLegalEntityId"
      :options="{
        locale: 'en-US',
        environment: 'test',
        fetchToken,
      }"
      :settings="{
        acceptedCountries: ['AD', 'US', 'NZ'],
      }"
    ></adyen-terms-of-service>
  </div>
</template>

<script setup lang="ts">
import '@adyen/kyc-components/experimental/terms-of-service';

const rootLegalEntityId = import.meta.env.VITE_ADYEN_LEGALENTITYID;

const fetchToken = async () => {
  try {
    const response = await fetch('/.netlify/functions/token');
    return response.json();
  } catch (error) {
    console.error('Error fetching token:', error);
  }
};
</script>

// src/App.tsx
import '@adyen/kyc-components/experimental/terms-of-service';

function App() {
  const fetchToken = async () => {
    try {
      const response = await fetch('/.netlify/functions/token');
      return response.json();
    } catch (error) {
      console.error('Error fetching token:', error);
    }
  };

  return (
    <div>
      ToS
      <adyen-terms-of-service
        options={{
          locale: 'en-US',
          environment: 'test',
          fetchToken,
        }}
        rootlegalentityid={import.meta.env.VITE_ADYEN_LEGALENTITYID}
        settings={{
          acceptedCountries: ['AD', 'US', 'NZ'],
        }}
      ></adyen-terms-of-service>
    </div>
  );
}

export default App;
